In [4]:
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 07:41:53 2019

@author: Sowmya
"""
import pandas as pd
import re
#User input
path=input()
df= pd.read_csv(path, header=None, sep = ',')
length=len(df.columns)
df.head()
#C:\E\Sowmya\calls-2k.dirty.csv
#C:\E\Sowmya\calls-4.csv

C:\E\Sowmya\calls-4.csv

,0,1,2,3,4
0,493abc93-e425-4d53-82a7-aa00710cf5fb,eve417,2017-03-16T22:39:00.000Z,2017-03-16T23:55:00.000Z,059c4d79-a44d-48fe-8ca4-e565b7361f52
1,493abc93-e425-4d53-82a7-aa00710cf5fb,eve386,2017-03-16T22:39:00.000Z,2017-03-16T23:57:00.000Z,f3d6b8e7-7e0b-49e2-ad20-a40e1198e0f3
2,493abc93-e425-4d53-82a7-aa00710cf5fb,dave072,2017-03-16T22:40:00.000Z,2017-03-16T23:56:00.000Z,2f3e4039-4206-4efb-b76d-5ce244bf1400
3,493abc93-e425-4d53-82a7-aa00710cf5fb,alice753,2017-03-16T22:41:00.000Z,2017-03-16T23:58:00.000Z,b58e620d-a7c5-4485-b73b-e9a60d5cb745
4,493abc93-e425-4d53-82a7-aa00710cf5fb,dave911,2017-03-16T22:41:00.000Z,2017-03-16T23:59:00.000Z,028a1d40-3866-4336-8e72-7426cc12d75a

In [2]:
length = len(df.columns)
#filter(df['Status']=='False')
#df=startdf
#Regexp to validate the datatime format
regpat = re.compile(r'^[1-9]{1}[0-9]{3}\-(0[1-9]|1[0-2])-(3[0-1]|0[1-9]|1[0-9]|2[0-9])T(0[0-9]|1[0-9]|2[0-3])\:\
([0-5][0-9])\:([0][0])\.[0]{3}Z$')
if length == 5:
    print(length)
    start=df[2].str.contains(regpat)
    #print(start)
    #df['Status']
    #df['ColumnLengthErr'] = length
    for CHECK in start:
        if not CHECK:
        #print(CHECK)
            df['Error1']='Start Time Format Mismatch'
        else:
            #print(CHECK)
            end=df[3].str.contains(regpat)
            for CHECK in end:
                if not CHECK:
                    #print(CHECK)
                    df['Error1']='End Time Format Mismatch' 
                else:
                    df['Error1']='None'
        newdf=df
               
else:
    #print("else")
    start=df[2].str.contains(regpat)
    #df['Status']
    df['ColumnLengthErr'] = length
    for CHECK in start:
        if not CHECK:
        #print(CHECK)
            df['Error1']='Start Time Format Mismatch'
        else:
            #print(CHECK)
            end=df[3].str.contains(regpat)
            for CHECK in end:
                if not CHECK:
                    #print(CHECK)
                    df['Error1']='End Time Format Mismatch'
                else:
                    df['Error1']='None'
                    
        df.to_csv('ErrValidation.txt', index=False)

5

C:\Program Files1\Anaconda\lib\site-packages\ipykernel_launcher.py:7: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  import sys
C:\Program Files1\Anaconda\lib\site-packages\ipykernel_launcher.py:17: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

In [5]:
newdf.head()

,0,1,2,3,4,Error1
0,493abc93-e425-4d53-82a7-aa00710cf5fb,eve417,2017-03-16T22:39:00.000Z,2017-03-16T23:55:00.000Z,059c4d79-a44d-48fe-8ca4-e565b7361f52,None
1,493abc93-e425-4d53-82a7-aa00710cf5fb,eve386,2017-03-16T22:39:00.000Z,2017-03-16T23:57:00.000Z,f3d6b8e7-7e0b-49e2-ad20-a40e1198e0f3,None
2,493abc93-e425-4d53-82a7-aa00710cf5fb,dave072,2017-03-16T22:40:00.000Z,2017-03-16T23:56:00.000Z,2f3e4039-4206-4efb-b76d-5ce244bf1400,None
3,493abc93-e425-4d53-82a7-aa00710cf5fb,alice753,2017-03-16T22:41:00.000Z,2017-03-16T23:58:00.000Z,b58e620d-a7c5-4485-b73b-e9a60d5cb745,None
4,493abc93-e425-4d53-82a7-aa00710cf5fb,dave911,2017-03-16T22:41:00.000Z,2017-03-16T23:59:00.000Z,028a1d40-3866-4336-8e72-7426cc12d75a,None